import type { InterviewBrief, ResearchPack } from "./deck-types";

export function mockResearch(_brief: InterviewBrief): ResearchPack {
  const sources = [
    {
      id: "src_001",
      title: "한국 디지털 콘텐츠 산업 백서 2025",
      publisher: "한국콘텐츠진흥원",
      year: 2025,
      grade: "A" as const,
      sourceType: "government" as const,
      usePolicy: "priority" as const,
    },
    {
      id: "src_002",
      title: "Global AI Market Outlook 2026",
      publisher: "Gartner",
      year: 2026,
      grade: "B" as const,
      sourceType: "research" as const,
      usePolicy: "allowed" as const,
    },
    {
      id: "src_003",
      title: "엔터프라이즈 SaaS 도입 현황 조사",
      publisher: "IDC Korea",
      year: 2025,
      grade: "A" as const,
      sourceType: "research" as const,
      usePolicy: "priority" as const,
    },
    {
      id: "src_004",
      title: "생성형 AI 사용자 조사",
      publisher: "Statista",
      year: 2026,
      grade: "B" as const,
      sourceType: "industry" as const,
      usePolicy: "allowed" as const,
    },
  ];
  const datasets = [
    {
      id: "dataset_001",
      title: "AI tool pilot adoption rate",
      sourceIds: ["src_003"],
      unit: "%",
      period: "2025",
      geography: "KR",
      definition: "국내 기업 중 업무용 AI 도구를 시범 도입 중인 비율",
      rows: [{ label: "도입 중", value: 67, year: 2025 }],
      uncertain: false,
    },
    {
      id: "dataset_002",
      title: "AI content creation market CAGR",
      sourceIds: ["src_001", "src_002"],
      unit: "%",
      period: "2025-2026",
      geography: "global",
      definition: "AI 기반 콘텐츠 제작 시장의 추정 연평균 성장률",
      rows: [{ label: "CAGR", value: 38, year: 2026 }],
      uncertain: false,
    },
  ];
  const claims = [
    {
      id: "claim_001",
      statement: "국내 기업의 67%가 AI 도구를 업무에 시범 도입 중이다.",
      sourceIds: ["src_003"],
      datasetIds: ["dataset_001"],
      confidence: "high" as const,
      hasNumber: true,
      needsUserReview: false,
      status: "supported" as const,
      slideCandidates: [2, 3],
      numericEvidence: [
        {
          id: "num_001",
          value: "67",
          unit: "%",
          baseYear: 2025,
          geography: "KR",
          definition: "업무용 AI 도구를 시범 도입 중인 국내 기업 비율",
          sourceId: "src_003",
          datasetId: "dataset_001",
        },
      ],
    },
    {
      id: "claim_002",
      statement: "AI 기반 콘텐츠 제작 시장은 연평균 38% 성장하고 있다.",
      sourceIds: ["src_001", "src_002"],
      datasetIds: ["dataset_002"],
      confidence: "high" as const,
      hasNumber: true,
      needsUserReview: false,
      status: "supported" as const,
      slideCandidates: [3],
      numericEvidence: [
        {
          id: "num_002",
          value: "38",
          unit: "%",
          baseYear: 2026,
          geography: "global",
          definition: "AI 기반 콘텐츠 제작 시장의 추정 연평균 성장률",
          sourceId: "src_002",
          datasetId: "dataset_002",
        },
      ],
    },
    {
      id: "claim_003",
      statement: "생성된 결과물의 검증 부재가 도입의 주요 장벽이다.",
      sourceIds: ["src_004"],
      datasetIds: [],
      confidence: "medium" as const,
      hasNumber: false,
      needsUserReview: false,
      status: "supported" as const,
      slideCandidates: [2, 4],
      numericEvidence: [],
    },
    {
      id: "claim_004",
      statement: "이 기능은 시장에서 강한 차별성을 가진다.",
      sourceIds: [],
      datasetIds: [],
      confidence: "assumption" as const,
      hasNumber: false,
      needsUserReview: true,
      status: "assumption" as const,
      slideCandidates: [5],
      numericEvidence: [],
    },
  ];
  const charts = [
    {
      id: "chart_001",
      title: "AI 도구 시범 도입 비율",
      chartType: "bar" as const,
      datasetId: "dataset_001",
      unit: "%",
      period: "2025",
      sourceIds: ["src_003"],
      slideCandidates: [3],
      uncertain: false,
    },
  ];
  const factCheckReport = {
    summary: "핵심 수치에는 source와 dataset metadata가 연결되어 있다.",
    generatedAt: Date.now(),
    fatalIssueCount: 0,
    issues: [
      {
        id: "issue_001",
        severity: "warning" as const,
        message: "claim_004는 시장 차별성 가설로 사용자 검토가 필요하다.",
        claimId: "claim_004",
        uncertain: true,
      },
    ],
    uncertainItems: ["claim_004는 출처 없는 가설로 표시됨"],
  };
  return {
    id: "res_" + Date.now().toString(36),
    sources,
    claims,
    datasets,
    charts,
    factCheckReport,
  };
}
