/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectProjectIdStepRouteImport } from './routes/project.$projectId.$step'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectProjectIdStepRoute = ProjectProjectIdStepRouteImport.update({
  id: '/project/$projectId/$step',
  path: '/project/$projectId/$step',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/project/$projectId/$step': typeof ProjectProjectIdStepRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/project/$projectId/$step': typeof ProjectProjectIdStepRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/project/$projectId/$step': typeof ProjectProjectIdStepRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/project/$projectId/$step'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/project/$projectId/$step'
  id: '__root__' | '/' | '/project/$projectId/$step'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectProjectIdStepRoute: typeof ProjectProjectIdStepRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$projectId/$step': {
      id: '/project/$projectId/$step'
      path: '/project/$projectId/$step'
      fullPath: '/project/$projectId/$step'
      preLoaderRoute: typeof ProjectProjectIdStepRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectProjectIdStepRoute: ProjectProjectIdStepRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
