import {
  evaluateApprovalProvenanceGate,
  type ProviderArtifactProvenance,
  type ProviderProvenanceIssue,
} from "./provider-provenance";
import type { LiveInterviewIssue, LiveInterviewStage } from "./live-interview-cutover";

export function liveCodexProvenanceIssues(
  stage: LiveInterviewStage,
  lineage: readonly ProviderArtifactProvenance[],
): readonly LiveInterviewIssue[] {
  const gate = evaluateApprovalProvenanceGate(lineage);
  const expectedPromptVersions =
    stage === "brief"
      ? ["interview_brief@v1"]
      : ["interview_questions@v1", "interview_questions_desktop@v1"];
  const gateIssues =
    gate.kind === "blocked" ? gate.issues.map((issue) => providerIssue(stage, issue)) : [];
  const modeIssues = lineage.flatMap((provenance) => [
    ...canonicalIdentityIssues(stage, provenance),
    ...(provenance.providerKind === "codex"
      ? []
      : [
          {
            code: "non_codex_interview_turn" as const,
            artifactId: provenance.artifactId,
            stage,
            message: "Interview questions and briefs must be generated by live Codex turns.",
          },
        ]),
    ...(provenance.executionMode === "production"
      ? []
      : [
          {
            code: "non_production_interview_turn" as const,
            artifactId: provenance.artifactId,
            stage,
            message: "Interview questions and briefs must come from production execution mode.",
          },
        ]),
    ...(expectedPromptVersions.includes(provenance.promptVersion)
      ? []
      : [
          {
            code: "interview_prompt_version_mismatch" as const,
            artifactId: provenance.artifactId,
            stage,
            message: `Interview ${stage} must use ${expectedPromptVersions.join(" or ")}.`,
          },
        ]),
  ]);

  return [...gateIssues, ...modeIssues];
}

function canonicalIdentityIssues(
  stage: LiveInterviewStage,
  provenance: ProviderArtifactProvenance,
): readonly LiveInterviewIssue[] {
  const identities = [provenance.artifactId, provenance.turnId, provenance.threadId];
  return identities.every((identity) => identity === undefined || identity === identity.trim())
    ? []
    : [
        {
          code: "noncanonical_interview_identity",
          artifactId: provenance.artifactId,
          stage,
          message: "Interview artifact, turn, and thread ids must be canonical.",
        },
      ];
}

export function questionRelationIssues(
  questionProvenance: ProviderArtifactProvenance,
  questionInputArtifactId: string,
): readonly LiveInterviewIssue[] {
  return hasInputArtifact(questionProvenance.inputArtifactIds, questionInputArtifactId)
    ? []
    : [
        {
          code: "question_missing_project_input" as const,
          artifactId: questionProvenance.artifactId,
          stage: "questions" as const,
          message: "The question turn must cite the project input artifact.",
        },
      ];
}

export function briefRelationIssues(
  questionProvenance: ProviderArtifactProvenance,
  briefProvenance: ProviderArtifactProvenance,
  answerArtifactId: string,
): readonly LiveInterviewIssue[] {
  return [
    ...(hasInputArtifact(briefProvenance.inputArtifactIds, questionProvenance.artifactId)
      ? []
      : [
          {
            code: "brief_missing_question_input" as const,
            artifactId: briefProvenance.artifactId,
            stage: "brief" as const,
            message: "The brief turn must cite the live question artifact as an input.",
          },
        ]),
    ...(hasInputArtifact(briefProvenance.inputArtifactIds, answerArtifactId)
      ? []
      : [
          {
            code: "brief_missing_answer_input" as const,
            artifactId: briefProvenance.artifactId,
            stage: "brief" as const,
            message: "The brief turn must cite the user answer bundle as an input.",
          },
        ]),
    ...(!sameIdentity(answerArtifactId, questionProvenance.artifactId)
      ? []
      : [
          {
            code: "brief_reused_question_answer" as const,
            artifactId: briefProvenance.artifactId,
            stage: "brief" as const,
            message: "The brief answer bundle must be separate from the live question artifact.",
          },
        ]),
    ...(!sameIdentity(briefProvenance.turnId, questionProvenance.turnId)
      ? []
      : [
          {
            code: "brief_reused_question_turn" as const,
            artifactId: briefProvenance.artifactId,
            stage: "brief" as const,
            message: "The brief must be generated by a second Codex turn after user answers.",
          },
        ]),
    ...(!sameIdentity(briefProvenance.artifactId, questionProvenance.artifactId)
      ? []
      : [
          {
            code: "brief_reused_question_artifact" as const,
            artifactId: briefProvenance.artifactId,
            stage: "brief" as const,
            message: "The brief must be persisted as a separate artifact from the questions.",
          },
        ]),
  ];
}

function hasInputArtifact(
  inputArtifactIds: readonly string[],
  expectedArtifactId: string,
): boolean {
  return inputArtifactIds.some((inputArtifactId) =>
    sameIdentity(inputArtifactId, expectedArtifactId),
  );
}

function sameIdentity(left: string | undefined, right: string | undefined): boolean {
  return left !== undefined && right !== undefined && left.trim() === right.trim();
}

function providerIssue(
  stage: LiveInterviewStage,
  issue: ProviderProvenanceIssue,
): LiveInterviewIssue {
  return {
    code: issue.code,
    message: issue.message,
    stage,
    ...(issue.artifactId === undefined ? {} : { artifactId: issue.artifactId }),
  };
}
