import {
  evaluateApprovalProvenanceGate,
  type ProviderArtifactProvenance,
  type ProviderProvenanceIssue,
} from "./provider-provenance";
import { inputArtifactIdentityIssues } from "./live-text-pipeline-input-identity";
import type {
  LiveTextPipelineCutoverInput,
  LiveTextPipelineIssue,
  LiveTextPipelineStage,
} from "./live-text-pipeline-cutover";

export function collectLiveTextPipelineProvenanceIssues(
  input: LiveTextPipelineCutoverInput,
): readonly LiveTextPipelineIssue[] {
  return [
    ...liveCodexProvenanceIssues("deck_plan", input.deckPlan.provenance),
    ...liveCodexProvenanceIssues("design_system", input.designSystem.provenance),
    ...liveCodexProvenanceIssues("layout_ir", input.layoutIr.provenance),
    ...canonicalIdentityIssues(input),
    ...inputArtifactIdentityIssues(input),
    ...turnIdentityIssues(input),
    ...artifactIdentityIssues(input),
    ...lineageIssues(input),
  ];
}

function liveCodexProvenanceIssues(
  stage: LiveTextPipelineStage,
  provenance: ProviderArtifactProvenance,
): readonly LiveTextPipelineIssue[] {
  const gate = evaluateApprovalProvenanceGate([provenance]);
  const expectedPromptVersions = promptVersionsForStage(stage);
  const gateIssues =
    gate.kind === "blocked" ? gate.issues.map((issue) => providerIssue(stage, issue)) : [];
  return [
    ...gateIssues,
    ...(provenance.providerKind === "codex"
      ? []
      : [
          {
            code: "non_codex_text_turn" as const,
            artifactId: provenance.artifactId,
            stage,
            message: "Deck plan, design system, and Layout IR must come from live Codex turns.",
          },
        ]),
    ...(provenance.executionMode === "production"
      ? []
      : [
          {
            code: "non_production_text_turn" as const,
            artifactId: provenance.artifactId,
            stage,
            message: "Text pipeline artifacts must come from production execution mode.",
          },
        ]),
    ...(expectedPromptVersions.includes(provenance.promptVersion)
      ? []
      : [
          {
            code: "text_pipeline_prompt_version_mismatch" as const,
            artifactId: provenance.artifactId,
            stage,
            message: `Text pipeline ${stage} must use ${expectedPromptVersions.join(" or ")}.`,
          },
        ]),
  ];
}

function promptVersionsForStage(stage: LiveTextPipelineStage): readonly string[] {
  if (stage === "deck_plan") return ["deck_plan@v1", "deck_plan_desktop@v1"];
  if (stage === "design_system") return ["design_system@v1", "design_system_desktop@v1"];
  return ["layout_ir@v1", "layout_ir_desktop@v1"];
}

function turnIdentityIssues(input: LiveTextPipelineCutoverInput): readonly LiveTextPipelineIssue[] {
  const turns = [
    input.deckPlan.provenance.turnId,
    input.designSystem.provenance.turnId,
    input.layoutIr.provenance.turnId,
  ];
  const completeTurns = turns
    .map((turnId) => normalizedIdentity(turnId))
    .filter((turnId): turnId is string => turnId !== undefined);
  return new Set(completeTurns).size === completeTurns.length
    ? []
    : [
        {
          code: "shared_live_turn",
          message: "Deck plan, design system, and Layout IR must be generated by separate turns.",
        },
      ];
}

function artifactIdentityIssues(
  input: LiveTextPipelineCutoverInput,
): readonly LiveTextPipelineIssue[] {
  const artifactIds = [
    input.deckPlan.provenance.artifactId,
    input.designSystem.provenance.artifactId,
    input.layoutIr.provenance.artifactId,
  ].map((artifactId) => artifactId.trim());
  return new Set(artifactIds).size === artifactIds.length
    ? []
    : [
        {
          code: "shared_live_artifact",
          message:
            "Deck plan, design system, and Layout IR must be persisted as separate artifacts.",
        },
      ];
}

function canonicalIdentityIssues(
  input: LiveTextPipelineCutoverInput,
): readonly LiveTextPipelineIssue[] {
  return [
    ...canonicalIdentityIssue("deck_plan", input.deckPlan.provenance),
    ...canonicalIdentityIssue("design_system", input.designSystem.provenance),
    ...canonicalIdentityIssue("layout_ir", input.layoutIr.provenance),
  ];
}

function canonicalIdentityIssue(
  stage: LiveTextPipelineStage,
  provenance: ProviderArtifactProvenance,
): readonly LiveTextPipelineIssue[] {
  const identities = [provenance.artifactId, provenance.turnId, provenance.threadId];
  return identities.every((identity) => identity === undefined || identity === identity.trim())
    ? []
    : [
        {
          code: "noncanonical_text_pipeline_identity",
          stage,
          artifactId: provenance.artifactId,
          message: "Text pipeline artifact, turn, and thread ids must be canonical.",
        },
      ];
}

function lineageIssues(input: LiveTextPipelineCutoverInput): readonly LiveTextPipelineIssue[] {
  return [
    ...deckPlanInputIssues(input),
    ...(hasInputArtifact(
      input.designSystem.provenance.inputArtifactIds,
      input.deckPlan.provenance.artifactId,
    )
      ? []
      : [
          {
            code: "missing_plan_input" as const,
            stage: "design_system" as const,
            artifactId: input.designSystem.provenance.artifactId,
            message: "Design System turn must cite the live Deck Plan artifact as input.",
          },
        ]),
    ...(hasInputArtifact(
      input.layoutIr.provenance.inputArtifactIds,
      input.deckPlan.provenance.artifactId,
    ) &&
    hasInputArtifact(
      input.layoutIr.provenance.inputArtifactIds,
      input.designSystem.provenance.artifactId,
    )
      ? []
      : [
          {
            code: "missing_design_input" as const,
            stage: "layout_ir" as const,
            artifactId: input.layoutIr.provenance.artifactId,
            message:
              "Layout IR turn must cite both live Deck Plan and Design System artifacts as inputs.",
          },
        ]),
  ];
}

function deckPlanInputIssues(
  input: LiveTextPipelineCutoverInput,
): readonly LiveTextPipelineIssue[] {
  const inputs = input.deckPlan.provenance.inputArtifactIds;
  return [
    ...(input.approvedBriefArtifactId.trim() !== input.approvedResearchPackArtifactId.trim()
      ? []
      : [
          {
            code: "shared_brief_research_input" as const,
            stage: "deck_plan" as const,
            artifactId: input.deckPlan.provenance.artifactId,
            message:
              "Deck Plan turn must cite distinct approved Brief and Live Research Pack artifacts.",
          },
        ]),
    ...(hasInputArtifact(inputs, input.approvedBriefArtifactId)
      ? []
      : [
          {
            code: "missing_brief_input" as const,
            stage: "deck_plan" as const,
            artifactId: input.deckPlan.provenance.artifactId,
            message: "Deck Plan turn must cite the approved Brief artifact as input.",
          },
        ]),
    ...(hasInputArtifact(inputs, input.approvedResearchPackArtifactId)
      ? []
      : [
          {
            code: "missing_research_input" as const,
            stage: "deck_plan" as const,
            artifactId: input.deckPlan.provenance.artifactId,
            message: "Deck Plan turn must cite the approved Live Research Pack artifact as input.",
          },
        ]),
  ];
}

function hasInputArtifact(
  inputArtifactIds: readonly string[],
  expectedArtifactId: string,
): boolean {
  return inputArtifactIds.some(
    (inputArtifactId) => inputArtifactId.trim() === expectedArtifactId.trim(),
  );
}

function normalizedIdentity(value: string | undefined): string | undefined {
  const trimmed = value?.trim();
  return trimmed === "" ? undefined : trimmed;
}

function providerIssue(
  stage: LiveTextPipelineStage,
  issue: ProviderProvenanceIssue,
): LiveTextPipelineIssue {
  return {
    code: issue.code,
    message: issue.message,
    stage,
    ...(issue.artifactId === undefined ? {} : { artifactId: issue.artifactId }),
  };
}
