import type { LiveTextProductionStage } from "./live-text-production-workflow";
import {
  evaluateApprovalProvenanceGate,
  type ProviderArtifactProvenance,
  type ProviderProvenanceIssue,
} from "./provider-provenance";
import type {
  LiveTextSmokeArtifact,
  LiveTextSmokeIssue,
  LiveTextSmokeIssueCode,
  LiveTextSmokeResumeEvidence,
} from "./live-text-smoke-gate";
import { textPathLineageIssues } from "./live-text-smoke-lineage";
import { textSmokePromptLineageIssues } from "./live-text-smoke-prompt-lineage";
import { resumeIssues } from "./live-text-smoke-resume";

const REQUIRED_STAGES = [
  "questions",
  "brief",
  "deck_plan",
  "design_system",
  "layout_ir",
] as const satisfies readonly LiveTextProductionStage[];

export function collectLiveTextSmokeIssues(
  input: {
    readonly artifacts: readonly LiveTextSmokeArtifact[];
    readonly resumeEvidence?: LiveTextSmokeResumeEvidence;
  },
  lineage: readonly ProviderArtifactProvenance[],
): readonly LiveTextSmokeIssue[] {
  return [
    ...stageIssues(input.artifacts),
    ...artifactIdentityReuseIssues(input.artifacts),
    ...textPathLineageIssues(input.artifacts),
    ...textSmokePromptLineageIssues(input.artifacts),
    ...input.artifacts.flatMap((artifact) => artifactIssues(artifact)),
    ...resumeIssues(input.resumeEvidence, lineage),
  ];
}

export function countAiArtifactsWithoutTurnId(artifacts: readonly LiveTextSmokeArtifact[]): number {
  return artifacts.filter((artifact) => !hasText(artifact.provenance.turnId)).length;
}

function stageIssues(artifacts: readonly LiveTextSmokeArtifact[]): readonly LiveTextSmokeIssue[] {
  return REQUIRED_STAGES.flatMap((stage) => {
    const artifactsForStage = artifacts.filter((artifact) => artifact.stage === stage);
    if (artifactsForStage.length === 0) {
      return [
        stageIssue("missing_text_stage", stage, `Live text smoke requires ${stage} artifact.`),
      ];
    }
    if (artifactsForStage.length > 1) {
      return [
        stageIssue(
          "duplicate_text_stage",
          stage,
          `Live text smoke has duplicate ${stage} artifacts.`,
        ),
      ];
    }
    return [];
  });
}

function artifactIssues(artifact: LiveTextSmokeArtifact): readonly LiveTextSmokeIssue[] {
  const gate = evaluateApprovalProvenanceGate([artifact.provenance]);
  const gateIssues =
    gate.kind === "blocked" ? gate.issues.map((item) => providerIssue(artifact, item)) : [];

  return [...gateIssues, ...liveCodexIssues(artifact), ...artifactIdentityIssues(artifact)];
}

function artifactIdentityReuseIssues(
  artifacts: readonly LiveTextSmokeArtifact[],
): readonly LiveTextSmokeIssue[] {
  const duplicateArtifactIds = duplicateValues(
    artifacts
      .map((artifact) => normalizedIdentity(artifact.provenance.artifactId))
      .filter((artifactId) => artifactId !== undefined),
  );
  const duplicateTurnIds = duplicateValues(
    artifacts
      .map((artifact) => normalizedIdentity(artifact.provenance.turnId))
      .filter((turnId) => turnId !== undefined),
  );

  return [
    ...duplicateArtifactIds.map((artifactId) => ({
      code: "duplicate_text_artifact_id" as const,
      artifactId,
      message: `Live text smoke artifacts must not reuse artifact id ${artifactId}.`,
    })),
    ...duplicateTurnIds.map((turnId) => ({
      code: "duplicate_text_turn_id" as const,
      message: `Live text smoke artifacts must not reuse turn id ${turnId}.`,
    })),
  ];
}

function liveCodexIssues(artifact: LiveTextSmokeArtifact): readonly LiveTextSmokeIssue[] {
  const provenance = artifact.provenance;
  return [
    ...(provenance.providerKind === "codex"
      ? []
      : [
          artifactIssue(
            "non_codex_text_artifact",
            artifact,
            "Live text smoke artifacts must be generated by Codex.",
          ),
        ]),
    ...(provenance.providerKind === "codex" || provenance.authMode === "codex_session"
      ? []
      : [
          artifactIssue(
            "non_codex_session_auth",
            artifact,
            "Live text smoke artifacts must use the authenticated Codex session.",
          ),
        ]),
    ...(provenance.executionMode === "production"
      ? []
      : [
          artifactIssue(
            "non_production_text_artifact",
            artifact,
            "Live text smoke artifacts must come from production execution mode.",
          ),
        ]),
  ];
}

function artifactIdentityIssues(artifact: LiveTextSmokeArtifact): readonly LiveTextSmokeIssue[] {
  return [
    ...(hasText(artifact.provenance.turnId)
      ? []
      : [
          artifactIssue(
            "text_artifact_missing_turn_id",
            artifact,
            "Every live text smoke artifact must carry a turn id.",
          ),
        ]),
    ...(hasText(artifact.provenance.threadId)
      ? []
      : [
          artifactIssue(
            "text_artifact_missing_thread_id",
            artifact,
            "Every live text smoke artifact must carry a thread id.",
          ),
        ]),
  ];
}

function providerIssue(
  artifact: LiveTextSmokeArtifact,
  issue: ProviderProvenanceIssue,
): LiveTextSmokeIssue {
  return {
    code: issue.code,
    message: issue.message,
    stage: artifact.stage,
    ...(issue.artifactId === undefined ? {} : { artifactId: issue.artifactId }),
  };
}

function stageIssue(
  code: LiveTextSmokeIssueCode,
  stage: LiveTextProductionStage,
  message: string,
): LiveTextSmokeIssue {
  return { code, stage, message };
}

function artifactIssue(
  code: LiveTextSmokeIssueCode,
  artifact: LiveTextSmokeArtifact,
  message: string,
): LiveTextSmokeIssue {
  return {
    code,
    message,
    stage: artifact.stage,
    artifactId: artifact.provenance.artifactId,
  };
}

function hasText(value: string | undefined): boolean {
  return value !== undefined && value.trim().length > 0;
}

function normalizedIdentity(value: string | undefined): string | undefined {
  const trimmed = value?.trim();
  return trimmed === "" ? undefined : trimmed;
}

function duplicateValues(values: readonly string[]): readonly string[] {
  const seen = new Set<string>();
  const duplicates = new Set<string>();
  for (const value of values) {
    if (seen.has(value)) {
      duplicates.add(value);
      continue;
    }
    seen.add(value);
  }
  return [...duplicates];
}
