import type { ProviderArtifactProvenance } from "./provider-provenance";
import type { LiveTextSmokeIssue, LiveTextSmokeResumeEvidence } from "./live-text-smoke-gate";

export function resumeIssues(
  evidence: LiveTextSmokeResumeEvidence | undefined,
  lineage: readonly ProviderArtifactProvenance[],
): readonly LiveTextSmokeIssue[] {
  if (evidence === undefined) {
    return [
      {
        code: "missing_resume_evidence",
        message: "Live text smoke requires evidence for a completed post-resume next turn.",
      },
    ];
  }

  const turnIds = new Set(
    lineage.flatMap((item) => {
      const turnId = normalizedIdentity(item.turnId);
      return turnId === undefined ? [] : [turnId];
    }),
  );
  const threadIdByTurnId = new Map(
    lineage.flatMap((item) => {
      const turnId = normalizedIdentity(item.turnId);
      const threadId = normalizedIdentity(item.threadId);
      return turnId === undefined || threadId === undefined ? [] : [[turnId, threadId] as const];
    }),
  );
  const previousTurnId = normalizedIdentity(evidence.previousTurnId);
  const nextTurnId = normalizedIdentity(evidence.nextTurnId);
  const resumeThreadId = normalizedIdentity(evidence.threadId);

  return [
    ...resumeLiveCodexIssues(evidence),
    ...(evidence.completed
      ? []
      : [
          {
            code: "resume_turn_not_completed" as const,
            message: "The post-resume turn must complete successfully.",
          },
        ]),
    ...(nextTurnId !== undefined
      ? []
      : [
          {
            code: "missing_resume_next_turn" as const,
            message: "The post-resume evidence must include the next turn id.",
          },
        ]),
    ...(previousTurnId !== undefined && turnIds.has(previousTurnId)
      ? []
      : [
          {
            code: "resume_previous_turn_not_in_lineage" as const,
            message: "The resumed project must continue from a produced text artifact turn.",
          },
        ]),
    ...(nextTurnId !== undefined && turnIds.has(nextTurnId)
      ? [
          {
            code: "resume_reused_existing_turn" as const,
            message: "The post-resume turn id must be a new turn after the text path.",
          },
        ]
      : []),
    ...(previousTurnId !== undefined &&
    resumeThreadId !== undefined &&
    threadIdByTurnId.get(previousTurnId) === resumeThreadId
      ? []
      : [
          {
            code: "resume_thread_mismatch" as const,
            message: "The post-resume turn must run on a text artifact thread.",
          },
        ]),
  ];
}

function resumeLiveCodexIssues(
  evidence: LiveTextSmokeResumeEvidence,
): readonly LiveTextSmokeIssue[] {
  return [
    ...(evidence.providerKind === "codex"
      ? []
      : [
          {
            code: "resume_non_codex_turn" as const,
            message: "The post-resume turn must be generated by Codex.",
          },
        ]),
    ...(evidence.authMode === "codex_session"
      ? []
      : [
          {
            code: "resume_non_codex_session_auth" as const,
            message: "The post-resume turn must use the authenticated Codex session.",
          },
        ]),
    ...(evidence.executionMode === "production"
      ? []
      : [
          {
            code: "resume_non_production_turn" as const,
            message: "The post-resume turn must come from production execution mode.",
          },
        ]),
  ];
}

function normalizedIdentity(value: string | undefined): string | undefined {
  const trimmed = value?.trim();
  return trimmed === "" ? undefined : trimmed;
}
