import {
  evaluateApprovalProvenanceGate,
  type ProviderArtifactProvenance,
  type ProviderProvenanceIssue,
} from "./provider-provenance";
import type { LiveInterviewIssue, LiveInterviewStage } from "./live-interview-cutover";

export function liveCodexProvenanceIssues(
  stage: LiveInterviewStage,
  lineage: readonly ProviderArtifactProvenance[],
): readonly LiveInterviewIssue[] {
  const gate = evaluateApprovalProvenanceGate(lineage);
  const expectedPromptVersions =
    stage === "brief"
      ? ["interview_brief@v1"]
      : ["interview_questions@v1", "interview_questions_desktop@v1"];
  const gateIssues =
    gate.kind === "blocked" ? gate.issues.map((issue) => providerIssue(stage, issue)) : [];
  const modeIssues = lineage.flatMap((provenance) => [
    ...(provenance.providerKind === "codex"
      ? []
      : [
          {
            code: "non_codex_interview_turn" as const,
            artifactId: provenance.artifactId,
            stage,
            message: "Interview questions and briefs must be generated by live Codex turns.",
          },
        ]),
    ...(provenance.executionMode === "production"
      ? []
      : [
          {
            code: "non_production_interview_turn" as const,
            artifactId: provenance.artifactId,
            stage,
            message: "Interview questions and briefs must come from production execution mode.",
          },
        ]),
    ...(expectedPromptVersions.includes(provenance.promptVersion)
      ? []
      : [
          {
            code: "interview_prompt_version_mismatch" as const,
            artifactId: provenance.artifactId,
            stage,
            message: `Interview ${stage} must use ${expectedPromptVersions.join(" or ")}.`,
          },
        ]),
  ]);

  return [...gateIssues, ...modeIssues];
}

export function questionRelationIssues(
  questionProvenance: ProviderArtifactProvenance,
  questionInputArtifactId: string,
): readonly LiveInterviewIssue[] {
  return questionProvenance.inputArtifactIds.includes(questionInputArtifactId)
    ? []
    : [
        {
          code: "question_missing_project_input" as const,
          artifactId: questionProvenance.artifactId,
          stage: "questions" as const,
          message: "The question turn must cite the project input artifact.",
        },
      ];
}

export function briefRelationIssues(
  questionProvenance: ProviderArtifactProvenance,
  briefProvenance: ProviderArtifactProvenance,
  answerArtifactId: string,
): readonly LiveInterviewIssue[] {
  return [
    ...(briefProvenance.inputArtifactIds.includes(questionProvenance.artifactId)
      ? []
      : [
          {
            code: "brief_missing_question_input" as const,
            artifactId: briefProvenance.artifactId,
            stage: "brief" as const,
            message: "The brief turn must cite the live question artifact as an input.",
          },
        ]),
    ...(briefProvenance.inputArtifactIds.includes(answerArtifactId)
      ? []
      : [
          {
            code: "brief_missing_answer_input" as const,
            artifactId: briefProvenance.artifactId,
            stage: "brief" as const,
            message: "The brief turn must cite the user answer bundle as an input.",
          },
        ]),
    ...(briefProvenance.turnId !== questionProvenance.turnId
      ? []
      : [
          {
            code: "brief_reused_question_turn" as const,
            artifactId: briefProvenance.artifactId,
            stage: "brief" as const,
            message: "The brief must be generated by a second Codex turn after user answers.",
          },
        ]),
  ];
}

function providerIssue(
  stage: LiveInterviewStage,
  issue: ProviderProvenanceIssue,
): LiveInterviewIssue {
  return {
    code: issue.code,
    message: issue.message,
    stage,
    ...(issue.artifactId === undefined ? {} : { artifactId: issue.artifactId }),
  };
}
