import type { LiveTextProductionStage } from "./live-text-production-workflow";
import {
  evaluateApprovalProvenanceGate,
  type ProviderArtifactProvenance,
  type ProviderProvenanceIssue,
} from "./provider-provenance";
import type {
  LiveTextSmokeArtifact,
  LiveTextSmokeIssue,
  LiveTextSmokeIssueCode,
  LiveTextSmokeResumeEvidence,
} from "./live-text-smoke-gate";
import { textPathLineageIssues } from "./live-text-smoke-lineage";
import { textSmokePromptLineageIssues } from "./live-text-smoke-prompt-lineage";

const REQUIRED_STAGES = [
  "questions",
  "brief",
  "deck_plan",
  "design_system",
  "layout_ir",
] as const satisfies readonly LiveTextProductionStage[];

export function collectLiveTextSmokeIssues(
  input: {
    readonly artifacts: readonly LiveTextSmokeArtifact[];
    readonly resumeEvidence?: LiveTextSmokeResumeEvidence;
  },
  lineage: readonly ProviderArtifactProvenance[],
): readonly LiveTextSmokeIssue[] {
  return [
    ...stageIssues(input.artifacts),
    ...textPathLineageIssues(input.artifacts),
    ...textSmokePromptLineageIssues(input.artifacts),
    ...input.artifacts.flatMap((artifact) => artifactIssues(artifact)),
    ...resumeIssues(input.resumeEvidence, lineage),
  ];
}

export function countAiArtifactsWithoutTurnId(artifacts: readonly LiveTextSmokeArtifact[]): number {
  return artifacts.filter((artifact) => !hasText(artifact.provenance.turnId)).length;
}

function stageIssues(artifacts: readonly LiveTextSmokeArtifact[]): readonly LiveTextSmokeIssue[] {
  return REQUIRED_STAGES.flatMap((stage) => {
    const artifactsForStage = artifacts.filter((artifact) => artifact.stage === stage);
    if (artifactsForStage.length === 0) {
      return [
        stageIssue("missing_text_stage", stage, `Live text smoke requires ${stage} artifact.`),
      ];
    }
    if (artifactsForStage.length > 1) {
      return [
        stageIssue(
          "duplicate_text_stage",
          stage,
          `Live text smoke has duplicate ${stage} artifacts.`,
        ),
      ];
    }
    return [];
  });
}

function artifactIssues(artifact: LiveTextSmokeArtifact): readonly LiveTextSmokeIssue[] {
  const gate = evaluateApprovalProvenanceGate([artifact.provenance]);
  const gateIssues =
    gate.kind === "blocked" ? gate.issues.map((item) => providerIssue(artifact, item)) : [];

  return [...gateIssues, ...liveCodexIssues(artifact), ...artifactIdentityIssues(artifact)];
}

function liveCodexIssues(artifact: LiveTextSmokeArtifact): readonly LiveTextSmokeIssue[] {
  const provenance = artifact.provenance;
  return [
    ...(provenance.providerKind === "codex"
      ? []
      : [
          artifactIssue(
            "non_codex_text_artifact",
            artifact,
            "Live text smoke artifacts must be generated by Codex.",
          ),
        ]),
    ...(provenance.providerKind === "codex" || provenance.authMode === "codex_session"
      ? []
      : [
          artifactIssue(
            "non_codex_session_auth",
            artifact,
            "Live text smoke artifacts must use the authenticated Codex session.",
          ),
        ]),
    ...(provenance.executionMode === "production"
      ? []
      : [
          artifactIssue(
            "non_production_text_artifact",
            artifact,
            "Live text smoke artifacts must come from production execution mode.",
          ),
        ]),
  ];
}

function artifactIdentityIssues(artifact: LiveTextSmokeArtifact): readonly LiveTextSmokeIssue[] {
  return [
    ...(hasText(artifact.provenance.turnId)
      ? []
      : [
          artifactIssue(
            "text_artifact_missing_turn_id",
            artifact,
            "Every live text smoke artifact must carry a turn id.",
          ),
        ]),
    ...(hasText(artifact.provenance.threadId)
      ? []
      : [
          artifactIssue(
            "text_artifact_missing_thread_id",
            artifact,
            "Every live text smoke artifact must carry a thread id.",
          ),
        ]),
  ];
}

function resumeIssues(
  evidence: LiveTextSmokeResumeEvidence | undefined,
  lineage: readonly ProviderArtifactProvenance[],
): readonly LiveTextSmokeIssue[] {
  if (evidence === undefined) {
    return [
      {
        code: "missing_resume_evidence",
        message: "Live text smoke requires evidence for a completed post-resume next turn.",
      },
    ];
  }

  const turnIds = new Set(lineage.map((item) => item.turnId).filter(isPresentString));
  const threadIdByTurnId = new Map(
    lineage.flatMap((item) =>
      isPresentString(item.turnId) && isPresentString(item.threadId)
        ? [[item.turnId, item.threadId] as const]
        : [],
    ),
  );

  return [
    ...resumeLiveCodexIssues(evidence),
    ...(evidence.completed
      ? []
      : [
          {
            code: "resume_turn_not_completed" as const,
            message: "The post-resume turn must complete successfully.",
          },
        ]),
    ...(hasText(evidence.nextTurnId)
      ? []
      : [
          {
            code: "missing_resume_next_turn" as const,
            message: "The post-resume evidence must include the next turn id.",
          },
        ]),
    ...(turnIds.has(evidence.previousTurnId)
      ? []
      : [
          {
            code: "resume_previous_turn_not_in_lineage" as const,
            message: "The resumed project must continue from a produced text artifact turn.",
          },
        ]),
    ...(hasText(evidence.nextTurnId) && turnIds.has(evidence.nextTurnId)
      ? [
          {
            code: "resume_reused_existing_turn" as const,
            message: "The post-resume turn id must be a new turn after the text path.",
          },
        ]
      : []),
    ...(threadIdByTurnId.get(evidence.previousTurnId) === evidence.threadId
      ? []
      : [
          {
            code: "resume_thread_mismatch" as const,
            message: "The post-resume turn must run on a text artifact thread.",
          },
        ]),
  ];
}

function resumeLiveCodexIssues(
  evidence: LiveTextSmokeResumeEvidence,
): readonly LiveTextSmokeIssue[] {
  return [
    ...(evidence.providerKind === "codex"
      ? []
      : [
          {
            code: "resume_non_codex_turn" as const,
            message: "The post-resume turn must be generated by Codex.",
          },
        ]),
    ...(evidence.authMode === "codex_session"
      ? []
      : [
          {
            code: "resume_non_codex_session_auth" as const,
            message: "The post-resume turn must use the authenticated Codex session.",
          },
        ]),
    ...(evidence.executionMode === "production"
      ? []
      : [
          {
            code: "resume_non_production_turn" as const,
            message: "The post-resume turn must come from production execution mode.",
          },
        ]),
  ];
}

function providerIssue(
  artifact: LiveTextSmokeArtifact,
  issue: ProviderProvenanceIssue,
): LiveTextSmokeIssue {
  return {
    code: issue.code,
    message: issue.message,
    stage: artifact.stage,
    ...(issue.artifactId === undefined ? {} : { artifactId: issue.artifactId }),
  };
}

function stageIssue(
  code: LiveTextSmokeIssueCode,
  stage: LiveTextProductionStage,
  message: string,
): LiveTextSmokeIssue {
  return { code, stage, message };
}

function artifactIssue(
  code: LiveTextSmokeIssueCode,
  artifact: LiveTextSmokeArtifact,
  message: string,
): LiveTextSmokeIssue {
  return {
    code,
    message,
    stage: artifact.stage,
    artifactId: artifact.provenance.artifactId,
  };
}

function isPresentString(value: string | undefined): value is string {
  return hasText(value);
}

function hasText(value: string | undefined): boolean {
  return value !== undefined && value.trim().length > 0;
}
